### ISSUE TITLE
why do you sample in testing?

### ISSUE THREAD

**Issue by ShellingFord221** [felix-laumann/Bayesian_CNN#8]
Hi, in your code, you sample 10 times in training to learn approximate parameters (Eq. 8 and Eq. 9), but why do you also sample 10 times in testing? Just only for uncertainty estimation? If I don't estimate sample's uncertainty, just want to test your BCNN on some dataset, should I also sample 10 times in testing? Or the accuracy may be decreased if I don't sample 10 times? Thanks!

**Comment by kumar-shridhar** [comment]
We sample in the test cases because we sample from the normal distribution which is used to update the mu value. If we do not sample during testing and average it out, we are dependent highly on the sampled value from the normal distribution. 
To minimize the dependency, we sample 10 times and then average the results which is why we sample 10 times. If we just sample once, we will some difference in the results every time (a slight difference not very large).
